version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    environment:
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "true"

      # OCIS_URL: the external domain / ip address of oCIS (with protocol, must always be https)
      OCIS_URL: "https://localhost:9200"

      # OCIS_LOG_LEVEL: error / info / ... / debug
      OCIS_LOG_LEVEL: info

      # admin user password, please change
      IDM_ADMIN_PASSWORD: "secretadminpassword" # this overrides the admin password from the configuration file

      # demo users
      IDM_CREATE_DEMO_USERS: "false"
