version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    environment:
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "true"

      # OCIS_URL: the external domain / ip address of oCIS (with protocol, must always be https)
      OCIS_URL: "https://localhost:9200"

      # OCIS_LOG_LEVEL: error / info / ... / debug
      OCIS_LOG_LEVEL: info
  # start a second ocis in a separate container with only the audit service
  # ocis-audit:
    # image: owncloud/ocis:latest
    # entrypoint:
    #   - /bin/sh
    # command: ["-c", "ocis audit server"]
